### ISSUE TITLE
f

### ISSUE THREAD

**Issue by NN77296** [RaduMC/AssetStudio#47]
litterally everything is broken, a ripoff of assetstudio

**Comment by RaduMC** [comment]
Useless kids

**Comment by NN77296** [comment]
worthless liar AHaHahahahAhAhaH "YOUR" SO COOOOOOOOOOOL
WOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

**Comment by NN77296** [comment]
i never thought the original would be this shitty,
useless tool ahahahaahahaa
get a life
